### ISSUE TITLE
[New Module] MMM-Ring

### ISSUE THREAD

**Issue by mdissel** [fewieden/MagicMirror-Hackathon#19]
Show the live stream on the magicmirror when someone is ringing on your Ring doorbell

See https://forum.magicmirror.builders/topic/8655/ring-doorbell-alarm-module/2

https://www.npmjs.com/package/ring-api

**Comment by fewieden** [comment]
Hopefully another dev joins, who has the required hardware to develop this module. I personally do not have one :/

**Comment by MMushovic** [comment]
Is anyone still working on this...?

**Comment by fewieden** [comment]
Hi @MMushovic, the hackathon was only 48h. I suggest you to push the forum thread of @mdissel https://forum.magicmirror.builders/topic/8655/ring-doorbell-alarm-module maybe there is a dev interested who also has the necessary hardware for it

**Comment by DustinBryant** [comment]
I just created this functionality and is now available as MMM-Ring. It will only show doorbell ring events on your ring product.

https://github.com/DustinBryant/MMM-Ring
