### ISSUE TITLE
[New Module] MMM-NewOnPlex

### ISSUE THREAD

**Issue by iwaldrum** [fewieden/MagicMirror-Hackathon#20]
It would be great to have a module that checks my plex server to see what has been recently added.

**Comment by fewieden** [comment]
Personally I don't have a plex server setup.

- Does it take long to set one up?
- Is there an API documentation?
- How should the module look like? A list?
- ...

**Comment by deg0nz** [comment]
This is actually quite a nice idea. I have multiple Plex instances to test this with.
I will think about building this. :)

**Comment by deg0nz** [comment]
@iwaldrum 
How did you imagine this? Just Text or also show minimized versions of the Movie/Series posters?

**Comment by deg0nz** [comment]
There's a Plex-API npm module. I'll leave this here for documentation:

https://www.npmjs.com/package/plex-api

Also there are some Plex users and Plex staff trying to document the API:

https://support.plex.tv/articles/201638786-plex-media-server-url-commands/
https://docs.google.com/document/d/19bTQr99oKn2pOpHcVtqidokbq9zup-K-mFy8JmII6uQ/edit
https://code.google.com/archive/p/plex-api/
https://github.com/Arcanemagus/plex-api/wiki/Plex-Web-API-Overview

**Comment by fewieden** [comment]
@deg0nz it would be great if you would find the time to actually build this.

**Comment by deg0nz** [comment]
Yeah, i think I'm gonna do this. Unfortunately it will take some time since I'm currently writing my Master Thesis, so there is not so much free time left currently... Maybe I'll find some time after that in summer. We'll see...

**Comment by fewieden** [comment]
@deg0nz good luck with your thesis!

**Comment by iwaldrum** [comment]
> @iwaldrum
> How did you imagine this? Just Text or also show minimized versions of the Movie/Series posters?

Thought it would be cool to have. Would be great to get a minimized version of the poster. I'll put some more thought into it..
