### ISSUE TITLE
[MMM-Slideshow] Only supports 5 pictures in random display order

### ISSUE THREAD

**Issue by xNoheal** [fewieden/MagicMirror-Hackathon#22]
I'm using this Module https://github.com/bryngo/MMM-Slideshow
I want it to be able to use x pictures in a normal order like the define order 

If you can take a look would be appreciate . 

- [x] fix picture support other than hardcoded 5
- [x] config option to enable/disable random display of pictures

**Comment by fewieden** [comment]
- [ ] fix picture support other than hardcoded 5
- [ ] config option to enable/disable random display of pictures

**Comment by fewieden** [comment]
https://github.com/bryngo/MMM-Slideshow/pull/1
